@startwbs
* Robotprogramming
** Dokumentation
*** WBS
*** GANTT
*** Iterationsplanerings modell
*** Projektdefintion
**** Riskanalys {Mattias}
**** Utbildningplan {Vincent}
**** Kostnadsplan {Zhonghao}
**** ......
** Konstruktion
*** Wall-E-Design (Want) {Otto, Zhonghao}
*** Sensorer
**** Ultraljud
*** Tippningmekanism {Otto}
** Kod
*** Flowcharts
**** Funktioner
***** init {Otto}
***** Rotation med x grader {Otto}
***** Släppa boken {Mattias}
***** Framåt (250 cm) {Vincent}
***** Rotation med identifiering av närmaste vägg {Zhonghao}
***** Köra fram till vägg med avstånd på 30 cm {Vincent}
**** Kodstruktur
***** Merge alla funktioner till robot.c {Otto}
***** Merge alla headers till en robot.h {Otto}
***** Läsbarhet {Alla}. 
****** Kommentarer
****** Struktur
****** Variabelnamn
****** Lagom storlek på funktioner
**** Program Mains 
***** Program_1 {Zhonghao}
***** Program_2 {Zhonghao}
***** Program_3 {Zhonghao}
***** Program _4 {Zhonghao}
*** Wants
**** Köra tillbaka till ursprungsplats
**** Låta som en robot
**** Blinka 
** Redovisning
*** Gemensam projektredovisning
' note bottom
' Alla skall hålla den enskilt (7 min)
' end note 
**** Ta fram en PPT
**** Sammanfattningsprotokoll

** Uppföljning, test och avslut
*** Provköra roboten inför demo.Tryck fast lösa delar {Otto}
*** Se till att robotens batteri är fullad {Zhonghao}
*** Demonstrera roboten {Otto}
*** Sorter upp lego bitarna i robotlådan {Mattias}
*** Lämna in robotlådan {Mattias}
*** Skriva egen kursrapport {Alla}
*** Skriva klart projektdef och se till att alla dokument finns {Vincent}
*** Göra klart muntliga presentationen {Vincent}
*** Vem som skrivit klart koden {Alla}
@endwbs