@startwbs
* Robotprogramming
** Dokumentation
*** WBS
*** GANTT
*** Iterationsplanerings modell
*** Projektdefintion
**** Riskanalys {Mattias}
**** Utbildningplan {Vincent}
**** Kostnadsplan {Zhonghao}
**** ......
** Konstruktion
*** Wall-E-Design (Want) {Otto, Zhonghao}
*** Sensorer
**** Ultraljud
*** Tippningmekanism {Otto}
** Kod
*** Flowcharts
**** Funktioner
***** init {Otto}
***** Rotation med x grader {Otto}
***** Släppa boken {Mattias}
***** Framåt (250 cm) {Vincent}
***** Rotation med identifiering av närmaste vägg {Zhonghao}
***** Köra fram till vägg med avstånd på 30 cm
**** Kodstruktur
***** Sammanställa funktion.c 
***** Header-fil 
***** Läsbarhet. 
****** Kommentarer
****** Struktur
****** Variabelnamn
****** Lagom storlek på funktioner
**** Program Mains 
***** Program 1
***** Program 2
***** Program 3
***** Program 4
** Redovisning
*** Gemensam projektredovisning
' note bottom
' Alla skall hålla den enskilt (7 min)
' end note 
**** Ta fram en PPT
**** Sammanfattningsprotokoll

** Test
*** Köra rakt fram
*** Rotera
*** Orientera sig 
*** Släppa bok
*** Program 1
*** Program 2
*** Program 3
*** Program 4
*** Återgå till samma plats 
@endwbs